/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as JudgesRouteImport } from './routes/judges'
import { Route as PlayRouteImport } from './routes/play'
import { Route as SolRouteImport } from './routes/sol'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as ApiSolRouteImport } from './routes/api/sol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesRoute = JudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const SolRoute = SolRouteImport.update({
  id: '/sol',
  path: '/sol',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSolRoute = ApiSolRouteImport.update({
  id: '/api/sol',
  path: '/api/sol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/judges': typeof JudgesRoute
  '/play': typeof PlayRoute
  '/sol': typeof SolRoute
  '/strategies': typeof StrategiesRoute
  '/api/sol': typeof ApiSolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/judges': typeof JudgesRoute
  '/play': typeof PlayRoute
  '/sol': typeof SolRoute
  '/strategies': typeof StrategiesRoute
  '/api/sol': typeof ApiSolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/judges': typeof JudgesRoute
  '/play': typeof PlayRoute
  '/sol': typeof SolRoute
  '/strategies': typeof StrategiesRoute
  '/api/sol': typeof ApiSolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-in'
    | '/judges'
    | '/play'
    | '/sol'
    | '/strategies'
    | '/api/sol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in'
    | '/judges'
    | '/play'
    | '/sol'
    | '/strategies'
    | '/api/sol'
  id:
    | '__root__'
    | '/'
    | '/check-in'
    | '/judges'
    | '/play'
    | '/sol'
    | '/strategies'
    | '/api/sol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInRoute: typeof CheckInRoute
  JudgesRoute: typeof JudgesRoute
  PlayRoute: typeof PlayRoute
  SolRoute: typeof SolRoute
  StrategiesRoute: typeof StrategiesRoute
  ApiSolRoute: typeof ApiSolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges': {
      id: '/judges'
      path: '/judges'
      fullPath: '/judges'
      preLoaderRoute: typeof JudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sol': {
      id: '/sol'
      path: '/sol'
      fullPath: '/sol'
      preLoaderRoute: typeof SolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sol': {
      id: '/api/sol'
      path: '/api/sol'
      fullPath: '/api/sol'
      preLoaderRoute: typeof ApiSolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInRoute: CheckInRoute,
  JudgesRoute: JudgesRoute,
  PlayRoute: PlayRoute,
  SolRoute: SolRoute,
  StrategiesRoute: StrategiesRoute,
  ApiSolRoute: ApiSolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
